import test from 'node:test';import assert from 'node:assert/strict';import * as Y from 'yjs';
import { createSession, verifySession } from '../server/auth.js';import { listProviderModels,validateBaseUrl,validateSource } from '../server/generator.js';import { applyOperations,bundleProject } from '../server/project.js';import { previewDocument } from '../server/preview.js';import { keepLastSuccess, shouldPromoteRevision } from '../server/orchestration.js';
test('server-signed attribution cannot be changed by the client',()=>{const token=createSession('test-secret',{roomId:'room-a',participantId:'alice-id',name:'Alice'});assert.deepEqual(verifySession('test-secret',token),{roomId:'room-a',participantId:'alice-id',name:'Alice'});const [,sig]=token.split('.');const changed=Buffer.from(JSON.stringify({roomId:'room-a',participantId:'bob-id',name:'Bob'})).toString('base64url');assert.equal(verifySession('test-secret',`${changed}.${sig}`),null)});
test('independent concurrent Yjs edits merge without lost text',()=>{const a=new Y.Doc(),b=new Y.Doc();Y.applyUpdate(b,Y.encodeStateAsUpdate(a));a.getText('brief').insert(0,'Alice idea. ');b.getText('brief').insert(0,'Bob idea. ');const au=Y.encodeStateAsUpdate(a),bu=Y.encodeStateAsUpdate(b);Y.applyUpdate(a,bu);Y.applyUpdate(b,au);assert.equal(a.getText('brief').toString(),b.getText('brief').toString());assert.match(a.getText('brief').toString(),/Alice idea/);assert.match(a.getText('brief').toString(),/Bob idea/)});
test('only the newest orchestration revision can be promoted',()=>{assert.equal(shouldPromoteRevision(4,5),false);assert.equal(shouldPromoteRevision(5,5),true)});
test('generation errors retain the last success and block unsafe code',()=>{const last={version:2};assert.equal(keepLastSuccess(last,undefined,new Error('compile failed')),last);assert.throws(()=>validateSource({app:'export default function App(){fetch("https://bad")}',css:'',summary:'x',decisions:[],conflicts:[]}),/blocked browser capability/)});
test('custom provider URLs require HTTPS except for local testing',()=>{assert.equal(validateBaseUrl('https://gateway.example/v1/'),'https://gateway.example/v1');assert.equal(validateBaseUrl('http://127.0.0.1:9999/v1'),'http://127.0.0.1:9999/v1');assert.throws(()=>validateBaseUrl('http://gateway.example/v1'),/must use HTTPS/);assert.throws(()=>validateBaseUrl('https://key:secret@gateway.example/v1'),/credentials/)});
test('provider model discovery returns exact account model IDs',async()=>{const original=globalThis.fetch;globalThis.fetch=(async(url,init)=>{assert.equal(String(url),'https://openrouter.ai/api/v1/models');assert.equal((init?.headers as Record<string,string>).Authorization,'Bearer test-key');return new Response(JSON.stringify({data:[{id:'openai/gpt-test',name:'GPT Test',context_length:128000}]}),{status:200})})as typeof fetch;try{assert.deepEqual(await listProviderModels('test-key','https://openrouter.ai/api/v1','openrouter'),[{id:'openai/gpt-test',name:'GPT Test',contextLength:128000}])}finally{globalThis.fetch=original}});
test('multi-file project compiles to an isolated React preview',async()=>{const files=applyOperations(undefined,[{type:'write',path:'src/App.tsx',content:"import{useState}from'react';export default function App(){const[x]=useState('working');localStorage.setItem('state',x);return <main>{x}</main>}"},{type:'write',path:'src/Card.tsx',content:"export const Card=()=> <article>Card</article>"}]),bundle=await bundleProject(files),html=previewDocument(bundle.javascript,bundle.css);assert.match(bundle.javascript,/createRoot/);assert.match(html,/connect-src 'none'/);assert.match(html,/cocreate-storage-ready/);assert.doesNotMatch(html,/OPENAI_API_KEY/);assert.throws(()=>applyOperations(files,[{type:'write',path:'../secret.ts',content:'no'}]),/invalid path/);assert.throws(()=>applyOperations(files,[{type:'write',path:'src/bad.ts',content:'fetch("https://bad")'}]),/blocked browser capability/)});
