import'dotenv/config';import http from'node:http';import path from'node:path';import{fileURLToPath}from'node:url';import express from'express';import{WebSocketServer}from'ws';import{createServer as createViteServer}from'vite';import{createSession,participantId,roomToken,verifySession,type Session}from'./auth.js';import{downloadableFiles}from'./project.js';import{previewDocument}from'./preview.js';import{RoomManager,type Room}from'./rooms.js';import{createZip}from'./zip.js';import type{AIFormat,AIProvider}from'../src/types.js';
type Options={port?:number;host?:string;serveClient?:boolean;baseUrl?:string;sessionSecret?:string;encryptionSecret?:string;debounceMs?:number;buildDebounceMs?:number;buildCooldownMs?:number;buildMaxWaitMs?:number;dataDir?:string};
const duration=(value:string|undefined,fallback:number,min:number,max:number)=>{const parsed=value===undefined?fallback:Number(value),safe=Number.isFinite(parsed)?parsed:fallback;return Math.max(min,Math.min(max,safe))};
export async function createCoCreateServer(options:Options={}){const app=express(),server=http.createServer(app),wss=new WebSocketServer({noServer:true}),secret=options.sessionSecret||process.env.SESSION_SECRET||'cocreate-local-session-secret',encryptionSecret=options.encryptionSecret||process.env.CREDENTIAL_ENCRYPTION_SECRET||secret,manager=new RoomManager({debounceMs:options.debounceMs??duration(process.env.AGENT_DEBOUNCE_MS,4_000,500,20_000),buildDebounceMs:options.buildDebounceMs??duration(process.env.BUILD_DEBOUNCE_MS,10_000,500,60_000),buildCooldownMs:options.buildCooldownMs??duration(process.env.BUILD_COOLDOWN_MS,30_000,0,300_000),buildMaxWaitMs:options.buildMaxWaitMs??duration(process.env.BUILD_MAX_WAIT_MS,60_000,5_000,600_000),encryptionSecret,baseUrl:options.baseUrl||process.env.PROVIDER_BASE_URL_OVERRIDE||process.env.OPENAI_BASE_URL,dataDir:options.dataDir});app.use(express.json({limit:'40kb'}));
  const authorize=(req:express.Request,res:express.Response):{session:Session;room:Room}|null=>{const token=(req.query.token||req.headers.authorization?.replace('Bearer ',''))as string|undefined,session=verifySession(secret,token);if(!session){res.status(401).json({error:'Your participant session is invalid. Rejoin the room.'});return null}const room=manager.get(String(req.params.id||session.roomId));if(!room||session.roomId!==room.id){res.status(404).json({error:'Room not found.'});return null}return{session,room}};
  const owner=(req:express.Request,res:express.Response)=>{const auth=authorize(req,res);if(!auth)return null;if(auth.room.ownerId!==auth.session.participantId){res.status(403).json({error:'Only the workspace owner can change the AI connection.'});return null}return auth};
  app.post('/api/rooms',(req,res)=>{const id=roomToken();manager.create(id);res.json({roomId:id,inviteUrl:`/r/${id}`})});
  app.post('/api/session',(req,res)=>{const roomId=String(req.body.roomId||''),name=String(req.body.name||'').trim().slice(0,40),room=manager.get(roomId);if(!room||!name)return res.status(400).json({error:'A valid room and display name are required.'});const old=verifySession(secret,req.body.token),id=old?.roomId===roomId?old.participantId:participantId();manager.join(room,id,name);res.json({token:createSession(secret,{roomId,participantId:id,name}),participantId:id,owner:room.ownerId===id})});
  app.get('/api/rooms/:id/state',(req,res)=>{const auth=authorize(req,res);if(!auth)return;if(!auth.room.participants.has(auth.session.participantId))manager.join(auth.room,auth.session.participantId,auth.session.name);res.json(manager.view(auth.room))});
  app.post('/api/rooms/:id/ai/test',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{const result=await manager.testConnection(String(req.body.apiKey||''),String(req.body.model||''),String(req.body.provider||'openai')as AIProvider,String(req.body.baseUrl||''),String(req.body.apiFormat||'responses')as AIFormat);res.json(result)}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/models',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.models(String(req.body.apiKey||''),String(req.body.provider||'openai')as AIProvider,String(req.body.baseUrl||''),String(req.body.apiFormat||'responses')as AIFormat))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/connect',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{await manager.connectAI(auth.room,String(req.body.apiKey||''),String(req.body.personalModel||''),String(req.body.builderModel||req.body.personalModel||''),String(req.body.provider||'openai')as AIProvider,String(req.body.baseUrl||''),String(req.body.apiFormat||'responses')as AIFormat);res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/disconnect',(req,res)=>{const auth=owner(req,res);if(!auth)return;manager.disconnectAI(auth.room);res.json({ok:true})});
  app.post('/api/rooms/:id/ai/connections',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.saveConnection(auth.room,{id:req.body.id?String(req.body.id):undefined,name:String(req.body.name||req.body.provider||''),provider:String(req.body.provider||'openai')as AIProvider,baseUrl:String(req.body.baseUrl||''),apiFormat:String(req.body.apiFormat||'chat-completions')as AIFormat,apiKey:String(req.body.apiKey||'')}))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/connections/:connectionId/models',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.discoverConnectionModels(auth.room,String(req.params.connectionId)))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/connections/:connectionId/check',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.checkCapabilities(auth.room,String(req.params.connectionId),String(req.body.model||'')))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.delete('/api/rooms/:id/ai/connections/:connectionId',(req,res)=>{const auth=owner(req,res);if(!auth)return;manager.disconnectConnection(auth.room,String(req.params.connectionId));res.json({ok:true})});
  app.post('/api/rooms/:id/ai/assignments',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{await manager.assignAI(auth.room,req.body.personal,req.body.builder,req.body.participantOverrides||{});res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/build',async(req,res)=>{const auth=authorize(req,res);if(!auth)return;try{await manager.buildNow(auth.room);res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/process',async(req,res)=>{const auth=authorize(req,res);if(!auth)return;try{await manager.processNow(auth.room,auth.session.participantId,String(req.body.correction||''));res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/runtime-error',(req,res)=>{const auth=authorize(req,res);if(!auth)return;manager.reportRuntimeError(auth.room,String(req.body.message||'Unknown error'),Number(req.body.version));res.json({ok:true})});
  app.get('/api/rooms/:id/download/:version',(req,res)=>{const auth=authorize(req,res);if(!auth)return;const v=manager.version(auth.room,Number(req.params.version));if(!v?.files)return res.status(404).send('Runnable project files are unavailable for this legacy version.');res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition',`attachment; filename="cocreate-${auth.room.id}-v${v.id}.zip"`);res.send(createZip(downloadableFiles(v.files)))});
  app.get('/preview/:id/:version',(req,res)=>{const room=manager.get(req.params.id),v=room&&manager.version(room,Number(req.params.version));if(!v)return res.status(404).send('Preview not found');res.setHeader('Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.type('html').send(previewDocument(v.bundle,v.css||v.source?.css||''))});
  server.on('upgrade',(req,socket,head)=>{try{const url=new URL(req.url||'','http://localhost');if(url.pathname!=='/ws')return socket.destroy();const roomId=url.searchParams.get('room')||'',session=verifySession(secret,url.searchParams.get('token')||''),room=manager.get(roomId);if(!session||session.roomId!==roomId||!room)return socket.destroy();if(!room.participants.has(session.participantId))manager.join(room,session.participantId,session.name);wss.handleUpgrade(req,socket,head,ws=>{manager.connect(room,ws,session.participantId);ws.on('message',(data,isBinary)=>manager.handleMessage(room,ws,Buffer.from(data as any),isBinary));ws.on('close',()=>manager.disconnect(room,ws))})}catch{socket.destroy()}});
  if(options.serveClient!==false){if(process.env.NODE_ENV==='production'){app.use(express.static(path.join(process.cwd(),'dist')));app.get('*path',(req,res)=>res.sendFile(path.join(process.cwd(),'dist','index.html')))}else{const vite=await createViteServer({configLoader:'runner',server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares)}}
  const start=()=>new Promise<{port:number;url:string}>(resolve=>{server.listen(options.port??Number(process.env.PORT||5173),options.host||'0.0.0.0',()=>{const address=server.address(),port=typeof address==='object'&&address?address.port:Number(options.port||5173);resolve({port,url:`http://localhost:${port}`})})});const stop=async()=>{for(const client of wss.clients)client.terminate();await new Promise<void>(resolve=>wss.close(()=>resolve()));manager.shutdown();if(server.listening)await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()))};return{app,server,manager,start,stop}}
const main=process.argv[1]&&path.resolve(process.argv[1])===path.resolve(fileURLToPath(import.meta.url));if(main){const instance=await createCoCreateServer();const info=await instance.start();console.log(`CoCreate ready at ${info.url}`)}
