import'dotenv/config';import http from'node:http';import path from'node:path';import{randomUUID}from'node:crypto';import{fileURLToPath}from'node:url';import express from'express';import{WebSocketServer}from'ws';import{createServer as createViteServer}from'vite';import{createSession,participantId,roomToken,verifySession,type Session}from'./auth.js';import{downloadableFiles}from'./project.js';import{previewDocument}from'./preview.js';import{RoomManager,type Room}from'./rooms.js';import{createZip}from'./zip.js';import{registerProjectRoutes}from'./project-routes.js';import{supabasePlatformFromEnv}from'./supabase-platform.js';import type{AIEffort,AIFormat,AIProvider,AIWorkflowMode,LegacyAISpecialty}from'../src/types.js';
type Options={port?:number;host?:string;serveClient?:boolean;baseUrl?:string;sessionSecret?:string;encryptionSecret?:string;debounceMs?:number;buildDebounceMs?:number;buildCooldownMs?:number;buildMaxWaitMs?:number;dataDir?:string};
const duration=(value:string|undefined,fallback:number,min:number,max:number)=>{const parsed=value===undefined?fallback:Number(value),safe=Number.isFinite(parsed)?parsed:fallback;return Math.max(min,Math.min(max,safe))};
export async function createCoCreateServer(options:Options={}){const app=express(),server=http.createServer(app),wss=new WebSocketServer({noServer:true}),secret=options.sessionSecret||process.env.SESSION_SECRET||'cocreate-local-session-secret',encryptionSecret=options.encryptionSecret||process.env.CREDENTIAL_ENCRYPTION_SECRET||secret,platformState=supabasePlatformFromEnv(),manager=new RoomManager({debounceMs:options.debounceMs??duration(process.env.AGENT_DEBOUNCE_MS,4_000,500,20_000),buildDebounceMs:options.buildDebounceMs??duration(process.env.BUILD_DEBOUNCE_MS,3_000,500,60_000),buildCooldownMs:options.buildCooldownMs??duration(process.env.BUILD_COOLDOWN_MS,30_000,0,300_000),buildMaxWaitMs:options.buildMaxWaitMs??duration(process.env.BUILD_MAX_WAIT_MS,60_000,5_000,600_000),encryptionSecret,baseUrl:options.baseUrl||process.env.PROVIDER_BASE_URL_OVERRIDE||process.env.OPENAI_BASE_URL,dataDir:options.dataDir,durableStore:platformState.platform||undefined});app.use(express.json({limit:'40kb'}));
  app.get('/__cocreate/app-health',(_req,res)=>platformState.error?res.status(503).json({status:'configuration-error',service:'cocreate-app',error:platformState.error}):res.json({status:'ok',service:'cocreate-app'}));
  app.get('/api/auth/config',(_req,res)=>res.status(platformState.error?503:200).json({mode:platformState.mode,configured:!platformState.error,error:platformState.error||undefined}));
  if(platformState.platform)registerProjectRoutes(app,platformState.platform,manager,secret);
  const authorize=(req:express.Request,res:express.Response):{session:Session;room:Room}|null=>{const token=(req.query.token||req.headers.authorization?.replace('Bearer ',''))as string|undefined,session=verifySession(secret,token);if(!session){res.status(401).json({error:'Your project session expired or is invalid. Sign in again.'});return null}if(session.role==='viewer'&&req.method!=='GET'){res.status(403).json({error:'Viewers cannot change this project.'});return null}const room=manager.rooms.get(String(req.params.id||session.roomId))||(platformState.mode==='local'?manager.get(String(req.params.id||session.roomId)):null);if(!room||session.roomId!==room.id){res.status(404).json({error:'Project not found or not hydrated.'});return null}return{session,room}};
  const owner=(req:express.Request,res:express.Response)=>{const auth=authorize(req,res);if(!auth)return null;if(auth.room.ownerId!==auth.session.participantId){res.status(403).json({error:'Only the workspace owner can change the AI connection.'});return null}return auth};
  app.post('/api/rooms',(req,res)=>{if(platformState.mode==='supabase')return res.status(404).json({error:'Create authenticated projects through /api/projects.'});const id=roomToken();manager.create(id);res.json({roomId:id,inviteUrl:`/r/${id}`})});
  app.post('/api/session',(req,res)=>{if(platformState.mode==='supabase')return res.status(403).json({error:'Room links cannot grant project access. Sign in and use a project membership.'});const roomId=String(req.body.roomId||''),name=String(req.body.name||'').trim().slice(0,40),room=manager.get(roomId);if(!room||!name)return res.status(400).json({error:'A valid room and display name are required.'});const old=verifySession(secret,req.body.token),id=old?.roomId===roomId?old.participantId:participantId();manager.join(room,id,name);res.json({token:createSession(secret,{roomId,participantId:id,name}),participantId:id,owner:room.ownerId===id})});
  app.get('/api/rooms/:id/state',(req,res)=>{const auth=authorize(req,res);if(!auth)return;if(!auth.room.participants.has(auth.session.participantId))manager.join(auth.room,auth.session.participantId,auth.session.name);res.json(manager.view(auth.room))});
  app.get('/api/rooms/:id/workflow/events',(req,res)=>{const auth=authorize(req,res);if(!auth)return;const after=Number(req.query.after||0),limit=Number(req.query.limit||30);if(!Number.isInteger(after)||after<0||!Number.isInteger(limit)||limit<1||limit>100)return res.status(400).json({error:'Use a non-negative event cursor and a limit from 1 to 100.'});res.json(manager.workflowActivity(auth.room,after,limit))});
  app.post('/api/rooms/:id/ai/test',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{const result=await manager.testConnection(String(req.body.apiKey||''),String(req.body.model||''),String(req.body.provider||'openai')as AIProvider,String(req.body.baseUrl||''),String(req.body.apiFormat||'responses')as AIFormat);res.json(result)}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/models',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.models(String(req.body.apiKey||''),String(req.body.provider||'openai')as AIProvider,String(req.body.baseUrl||''),String(req.body.apiFormat||'responses')as AIFormat))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/connect',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{await manager.connectAI(auth.room,String(req.body.apiKey||''),String(req.body.personalModel||''),String(req.body.builderModel||req.body.personalModel||''),String(req.body.provider||'openai')as AIProvider,String(req.body.baseUrl||''),String(req.body.apiFormat||'responses')as AIFormat);res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/disconnect',(req,res)=>{const auth=owner(req,res);if(!auth)return;manager.disconnectAI(auth.room);res.json({ok:true})});
  app.post('/api/rooms/:id/ai/connections',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.saveConnection(auth.room,{id:req.body.id?String(req.body.id):undefined,name:String(req.body.name||req.body.provider||''),provider:String(req.body.provider||'openai')as AIProvider,baseUrl:String(req.body.baseUrl||''),apiFormat:String(req.body.apiFormat||'chat-completions')as AIFormat,apiKey:String(req.body.apiKey||'')}))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/connections/:connectionId/models',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.discoverConnectionModels(auth.room,String(req.params.connectionId)))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/connections/:connectionId/check',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{res.json(await manager.checkCapabilities(auth.room,String(req.params.connectionId),String(req.body.model||'')))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.delete('/api/rooms/:id/ai/connections/:connectionId',(req,res)=>{const auth=owner(req,res);if(!auth)return;manager.disconnectConnection(auth.room,String(req.params.connectionId));res.json({ok:true})});
  app.post('/api/rooms/:id/ai/assignments',async(req,res)=>{const auth=owner(req,res);if(!auth)return;try{await manager.assignAI(auth.room,req.body.personal,req.body.builder,req.body.participantOverrides||{});res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  const legacySpecialties=new Set<LegacyAISpecialty>(['general','engineer','designer','web_developer','motion_designer']),workflowModes=new Set<AIWorkflowMode>(['developer','analyst','researcher']),resolveWorkflowMode=(mode:unknown,specialty:unknown):AIWorkflowMode=>{const requested=String(mode||'');if(workflowModes.has(requested as AIWorkflowMode))return requested as AIWorkflowMode;if(legacySpecialties.has(String(specialty||'') as LegacyAISpecialty))return'developer';return'developer'};
  app.get('/api/rooms/:id/ai/recommendation',(req,res)=>{const auth=owner(req,res);if(!auth)return;const requested=String(req.query.mode||''),workflowMode=resolveWorkflowMode(req.query.mode,req.query.specialty),effort=String(req.query.effort||'medium')as AIEffort;if((requested&&!workflowModes.has(requested as AIWorkflowMode))||!['light','medium','high','extra'].includes(effort))return res.status(400).json({error:'Choose Developer, Analyst, or Researcher and a supported effort level.'});res.json(manager.recommendAI(auth.room,workflowMode,effort))});
  app.post('/api/rooms/:id/ai/recommendation',(req,res)=>{const auth=owner(req,res);if(!auth)return;try{const requested=String(req.body.mode||''),workflowMode=resolveWorkflowMode(req.body.mode,req.body.specialty),effort=String(req.body.effort||'medium')as AIEffort;if((requested&&!workflowModes.has(requested as AIWorkflowMode))||!['light','medium','high','extra'].includes(effort))return res.status(400).json({error:'Choose Developer, Analyst, or Researcher and a supported effort level.'});res.json(manager.applyRecommendedAI(auth.room,workflowMode,effort,Number(req.body.maximumSpendUsd)))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/ai/effort',(req,res)=>{const auth=owner(req,res);if(!auth)return;try{const effort=String(req.body.effort||'')as AIEffort;if(!['light','medium','high','extra'].includes(effort))return res.status(400).json({error:'Choose Light, Medium, High, or Extra effort.'});res.json(manager.setAIEffort(auth.room,effort))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/build',async(req,res)=>{const auth=authorize(req,res);if(!auth)return;try{await manager.buildNow(auth.room);res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/submit',async(req,res)=>{const auth=authorize(req,res);if(!auth)return;try{const requestId=String(req.body.requestId||'');if(!requestId||requestId.length>100)return res.status(400).json({error:'A valid submission request ID is required.'});res.json(await manager.submitChanges(auth.room,auth.session.participantId,requestId))}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/process',async(req,res)=>{const auth=authorize(req,res);if(!auth)return;try{await manager.processNow(auth.room,auth.session.participantId,String(req.body.correction||''));res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/reinterpret',async(req,res)=>{const auth=authorize(req,res);if(!auth)return;try{await manager.reinterpretLatest(auth.room,auth.session.participantId);res.json({ok:true})}catch(error){res.status(400).json({error:error instanceof Error?error.message:String(error)})}});
  app.post('/api/rooms/:id/runtime-error',(req,res)=>{const auth=authorize(req,res);if(!auth)return;manager.reportRuntimeError(auth.room,String(req.body.message||'Unknown error'),Number(req.body.version));res.json({ok:true})});
  app.get('/api/rooms/:id/download/:version',(req,res)=>{const auth=authorize(req,res);if(!auth)return;const v=manager.version(auth.room,Number(req.params.version));if(!v?.files)return res.status(404).send('Runnable project files are unavailable for this legacy version.');res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition',`attachment; filename="cocreate-${auth.room.id}-v${v.id}.zip"`);res.send(createZip(downloadableFiles(v.files)))});
  app.get('/preview/:id/:version',(req,res)=>{const auth=platformState.mode==='supabase'?authorize(req,res):null;if(platformState.mode==='supabase'&&!auth)return;const room=auth?.room||manager.get(req.params.id),v=room&&manager.version(room,Number(req.params.version));if(!v)return res.status(404).send('Preview not found');res.setHeader('Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; frame-ancestors 'self'");res.type('html').send(previewDocument(v.bundle,v.css||v.source?.css||''))});
  const rejectUpgrade=(socket:import('node:stream').Duplex,status:number,category:string,correlationId:string)=>{const reason=status===401?'Unauthorized':status===404?'Not Found':'Bad Request';console.warn(JSON.stringify({event:'collaboration.upgrade_rejected',category,correlationId}));socket.end(`HTTP/1.1 ${status} ${reason}\r\nConnection: close\r\nContent-Length: 0\r\n\r\n`)};
  server.on('upgrade',(req,socket,head)=>{const correlationId=String(req.headers['cf-ray']||randomUUID());try{const url=new URL(req.url||'','http://localhost');if(url.pathname!=='/ws')return rejectUpgrade(socket,404,'unknown_path',correlationId);const origin=String(req.headers.origin||''),configuredOrigins=String(process.env.COCREATE_APP_ORIGINS||'').split(',').map(item=>item.trim()).filter(Boolean);if(platformState.mode==='supabase'&&(!origin||(configuredOrigins.length&&!configuredOrigins.includes(origin))))return rejectUpgrade(socket,403,'invalid_origin',correlationId);const roomId=url.searchParams.get('room')||'',session=verifySession(secret,url.searchParams.get('token')||'');if(!session||session.roomId!==roomId)return rejectUpgrade(socket,401,'invalid_session',correlationId);const room=manager.rooms.get(roomId)||(platformState.mode==='local'?manager.get(roomId):null);if(!room)return rejectUpgrade(socket,404,'missing_room',correlationId);if(!room.participants.has(session.participantId))manager.join(room,session.participantId,session.name);wss.handleUpgrade(req,socket,head,ws=>{const connectionId=randomUUID(),expiresAt=session.exp?session.exp*1000:undefined;console.info(JSON.stringify({event:'collaboration.connected',connectionId,correlationId}));manager.connect(room,ws,session.participantId,session.role||'editor',expiresAt);const expiryTimer=expiresAt?setTimeout(()=>ws.close(4401,'Project ticket expired'),Math.max(1,expiresAt-Date.now())):undefined;ws.on('message',(data,isBinary)=>manager.handleMessage(room,ws,Buffer.from(data as any),isBinary));ws.on('close',code=>{if(expiryTimer)clearTimeout(expiryTimer);console.info(JSON.stringify({event:'collaboration.disconnected',connectionId,code}));manager.disconnect(room,ws)})})}catch{rejectUpgrade(socket,400,'malformed_request',correlationId)}});
  if(options.serveClient!==false){if(process.env.NODE_ENV==='production'){app.use(express.static(path.join(process.cwd(),'dist')));app.get('*path',(req,res)=>res.sendFile(path.join(process.cwd(),'dist','index.html')))}else{const vite=await createViteServer({configLoader:'runner',server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares)}}
  const start=()=>new Promise<{port:number;url:string}>(resolve=>{server.listen(options.port??Number(process.env.PORT||5173),options.host||'0.0.0.0',()=>{const address=server.address(),port=typeof address==='object'&&address?address.port:Number(options.port||5173);resolve({port,url:`http://localhost:${port}`})})});const stop=async()=>{for(const client of wss.clients)client.terminate();await new Promise<void>(resolve=>wss.close(()=>resolve()));manager.shutdown();if(server.listening)await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()))};return{app,server,manager,start,stop}}
const main=process.argv[1]&&path.resolve(process.argv[1])===path.resolve(fileURLToPath(import.meta.url));if(main){const instance=await createCoCreateServer();const info=await instance.start();console.log(`CoCreate ready at ${info.url}`)}
