import type express from 'express';
import type { RoomManager } from './rooms.js';
import { createSession } from './auth.js';
import type { ProjectRole, SupabasePlatform } from './supabase-platform.js';
import type { InvitationEmailSender } from './invitation-email.js';

const bearer=(req:express.Request)=>req.headers.authorization?.replace(/^Bearer\s+/i,'')||'';
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const status=(error:unknown)=>Number((error as {status?:number})?.status)||400;
const displayName=(user:{email?:string;user_metadata?:Record<string,unknown>})=>String(user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'Collaborator').slice(0,40);
const appOrigin=()=>String(process.env.COCREATE_PUBLIC_ORIGIN||process.env.COCREATE_APP_ORIGINS||'http://localhost:5173').split(',').map(value=>value.trim()).find(Boolean)||'http://localhost:5173';

export function registerProjectRoutes(app:express.Express,platform:SupabasePlatform,manager:RoomManager,sessionSecret:string,emailSender:InvitationEmailSender,ticketTtlSeconds=300){
  app.get('/api/projects',async(req,res)=>{try{res.json(await platform.listProjects(bearer(req),{search:String(req.query.search||''),archived:req.query.archived==='true',offset:Number(req.query.offset||0),limit:Number(req.query.limit||30)}))}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.post('/api/projects',async(req,res)=>{try{const project=await platform.createProject(bearer(req),String(req.body.title||'Untitled project'),String(req.body.workflowMode||'developer')as 'developer'|'analyst'|'researcher');const room=manager.hydrate(project.id,{ownerId:project.ownerId,participants:[],ai:{mode:'disconnected'},persistRevision:0});manager.join(room,project.ownerId,'Owner');res.status(201).json(project)}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.patch('/api/projects/:id',async(req,res)=>{try{const user=await platform.verifyUser(bearer(req));res.json(await platform.updateProject(String(req.params.id),user.id,{title:req.body.title===undefined?undefined:String(req.body.title),archived:req.body.archived===undefined?undefined:Boolean(req.body.archived)}))}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.post('/api/projects/:id/session',async(req,res)=>{try{const accessToken=bearer(req),user=await platform.verifyUser(accessToken),projectId=String(req.params.id),role=await platform.requireMembership(projectId,user.id);let room=manager.rooms.get(projectId);if(!room){const snapshot=await platform.loadSnapshot(projectId);room=manager.hydrate(projectId,snapshot||{ownerId:role==='owner'?user.id:null,participants:[],ai:{mode:'disconnected'},persistRevision:0})}const name=displayName(user);manager.join(room,user.id,name);const exp=Math.floor(Date.now()/1000)+ticketTtlSeconds,token=createSession(sessionSecret,{roomId:projectId,participantId:user.id,accountId:user.id,name,role,exp});res.json({token,participantId:user.id,role,expiresAt:new Date(exp*1000).toISOString()})}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.get('/api/projects/:id/sharing',async(req,res)=>{try{const user=await platform.verifyUser(bearer(req));res.json(await platform.listSharing(String(req.params.id),user.id))}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.post('/api/projects/:id/invites',async(req,res)=>{try{const user=await platform.verifyUser(bearer(req)),projectId=String(req.params.id),role=String(req.body.role||'editor')as Exclude<ProjectRole,'owner'>;if(!['editor','viewer'].includes(role))return res.status(400).json({error:'Invites may grant editor or viewer access.'});const raw:unknown[]=Array.isArray(req.body.emails)?req.body.emails:[req.body.email],emails:string[]=[...new Set(raw.map(value=>String(value||'').trim().toLowerCase()).filter(Boolean))];if(!emails.length||emails.length>10)return res.status(400).json({error:'Enter between 1 and 10 recipient email addresses.'});const projectTitle=await platform.projectTitle(projectId),inviterName=displayName(user),results:Array<Record<string,unknown>>=[];for(const email of emails){try{const invite=await platform.createInvite(projectId,user.id,email,role,Number(req.body.ttlHours||72)),inviteUrl=`${appOrigin()}/invite/${encodeURIComponent(invite.token)}`,delivery=await emailSender.send({invitationId:invite.id,recipientEmail:invite.email,inviterName,projectTitle,role,inviteUrl});await platform.recordInviteDelivery(invite.id,delivery);results.push({id:invite.id,email:invite.email,role,expiresAt:invite.expiresAt,deliveryState:delivery.state,deliveryError:delivery.error,shareUrl:inviteUrl})}catch(error){results.push({email,role,deliveryState:'failed',deliveryError:message(error)})}}res.status(201).json({invitations:results})}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.post('/api/projects/:id/invites/:inviteId/resend',async(req,res)=>{try{const user=await platform.verifyUser(bearer(req)),projectId=String(req.params.id),invite=await platform.resendInvite(projectId,user.id,String(req.params.inviteId),Number(req.body.ttlHours||72)),projectTitle=await platform.projectTitle(projectId),inviteUrl=`${appOrigin()}/invite/${encodeURIComponent(invite.token)}`,delivery=await emailSender.send({invitationId:invite.id,recipientEmail:invite.email,inviterName:displayName(user),projectTitle,role:invite.role,inviteUrl});await platform.recordInviteDelivery(invite.id,delivery);res.status(201).json({id:invite.id,email:invite.email,role:invite.role,expiresAt:invite.expiresAt,deliveryState:delivery.state,deliveryError:delivery.error,shareUrl:inviteUrl})}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.delete('/api/projects/:id/invites/:inviteId',async(req,res)=>{try{const user=await platform.verifyUser(bearer(req));res.json(await platform.revokeInvite(String(req.params.id),user.id,String(req.params.inviteId)))}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.patch('/api/projects/:id/members/:memberId',async(req,res)=>{try{const user=await platform.verifyUser(bearer(req)),role=req.body.role===undefined?undefined:String(req.body.role)as Exclude<ProjectRole,'owner'>;if(role&&!['editor','viewer'].includes(role))return res.status(400).json({error:'Members may be editors or viewers.'});res.json(await platform.updateMember(String(req.params.id),user.id,String(req.params.memberId),{role,canShare:req.body.canShare===undefined?undefined:Boolean(req.body.canShare)}))}catch(error){res.status(status(error)).json({error:message(error)})}});
  app.post('/api/invites/accept',async(req,res)=>{try{res.json({projectId:await platform.acceptInvite(bearer(req),String(req.body.token||''))})}catch(error){res.status(status(error)).json({error:message(error)})}});
}
