import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const origin='http://localhost:5173',output=path.resolve('artifacts/supabase-projects/login.png'),chrome='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',port=9900+(process.pid%80),profile=path.join(os.tmpdir(),`cocreate-auth-capture-${process.pid}`),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
fs.mkdirSync(path.dirname(output),{recursive:true});fs.mkdirSync(profile,{recursive:true});
const browser=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--no-first-run',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});let socket;
try{let target;for(let attempt=0;attempt<60&&!target;attempt++){await wait(100);try{target=await fetch(`http://127.0.0.1:${port}/json/new?about:blank`,{method:'PUT'}).then(response=>response.json())}catch{}}if(!target)throw new Error('Chrome did not start.');socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})});let id=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(!message.id||!pending.has(message.id))return;const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result)});const call=(method,params={})=>new Promise((resolve,reject)=>{const callId=++id;pending.set(callId,{resolve,reject});socket.send(JSON.stringify({id:callId,method,params}))});await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:`${origin}/login`});for(let attempt=0;attempt<40;attempt++){const ready=await call('Runtime.evaluate',{expression:"document.querySelector('button')?.textContent.includes('Google')",returnByValue:true});if(ready.result.value)break;await wait(100)}const layout=await call('Runtime.evaluate',{expression:"({title:document.querySelector('h1')?.textContent,button:document.querySelector('button')?.textContent,overflow:document.documentElement.scrollWidth>innerWidth})",returnByValue:true});if(layout.result.value.title!=='Build together'||!layout.result.value.button?.includes('Google')||layout.result.value.overflow)throw new Error(`Login UI check failed: ${JSON.stringify(layout.result.value)}`);const shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(output,Buffer.from(shot.data,'base64'));console.log(JSON.stringify({output,layout:layout.result.value}))}finally{socket?.close();browser.kill()}
