import { useEffect, useRef, useState } from 'react';
import type { IntentCommand, IntentCommandResult, IntentTarget, InterpretationClassification, InterpretationIntentCategory, RoomView, SharedRequirementSource } from '../shared/types';
import './intent-review.css';

type Edit={target:IntentTarget;specificationRevision:number;action:'correct'|'withdraw';text:string;category:InterpretationIntentCategory;classification:'explicit_request'|'proposal'|'question'};
const caption=(value:InterpretationClassification)=>value==='explicit_request'?'Explicit request':value.replaceAll('_',' ');
export function IntentReview({state,participantId,canEdit,shownRevision,onClose,onCommand,onBuild}:{state:RoomView;participantId?:string;canEdit:boolean;shownRevision:number;onClose:()=>void;onCommand:(command:IntentCommand)=>Promise<IntentCommandResult>;onBuild:(requestId:string)=>Promise<unknown>}) {
  const dialog=useRef<HTMLDialogElement>(null),key=`cocreate-intent-command-${state.roomId}-${participantId}`;
  const pending=useRef<IntentCommand|undefined>(undefined),buildRequest=useRef<string|undefined>(undefined);
  const [edit,setEdit]=useState<Edit>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[cacheError,setCacheError]=useState('');
  const persistPending=(command?:IntentCommand)=>{try{if(command)localStorage.setItem(key,JSON.stringify(command));else localStorage.removeItem(key);}catch{setCacheError('Device recovery copy is unavailable. Keep this page open to retry an uncertain request.');}};
  useEffect(()=>{const element=dialog.current!,opener=document.activeElement as HTMLElement|null;element.showModal();return()=>{element.close();if(opener?.isConnected)opener.focus();};},[]);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null') as IntentCommand|null;if(saved){pending.current=saved;setEdit({...saved,text:saved.text||'',category:saved.category||'feature',classification:saved.classification||'explicit_request'});setMessage('A previous intent request has an uncertain response. Retry it with the same request ID.');}}catch{setCacheError('Device recovery copy could not be read.');}},[key]);
  const historical=shownRevision!==state.specificationRevision;
  const requirements=historical?(state.requirementRevisions||[]).find(item=>item.revision===shownRevision)?.accepted||[]:state.requirements;
  function begin(target:IntentTarget,text:string,category:InterpretationIntentCategory,classification:InterpretationClassification,action:'correct'|'withdraw'){
    pending.current=undefined;persistPending();setError('');setMessage('');
    setEdit({target,text,category:category==='withdrawal'?'feature':category,classification:classification==='proposal'?'proposal':classification==='question'?'question':'explicit_request',action,specificationRevision:state.specificationRevision});
  }
  const sources=(values:SharedRequirementSource[])=>values.map((source,index)=><p key={index}>{source.participantName} · document r{source.documentRevision} · edits {source.editSeqs.join(', ')||'recorded correction'} · {source.authority?.replaceAll('_',' ')||'legacy attribution'}{source.passages.map((passage,i)=><small key={i}>“{passage}”</small>)}</p>);
  async function submit(event:React.FormEvent){event.preventDefault();if(!edit||busy)return;setBusy(true);setError('');
    const command=pending.current||{requestId:crypto.randomUUID(),specificationRevision:edit.specificationRevision,target:edit.target,action:edit.action,
      ...(edit.action==='correct'?{text:edit.text,category:edit.category,classification:edit.classification}:{})};
    pending.current=command;persistPending(command);
    try{const result=await onCommand(command);pending.current=undefined;persistPending();setEdit(undefined);setMessage(`Intent ${result.action==='withdraw'?'withdrawn':'saved'} at specification r${result.specificationRevision}.${result.buildPending?' Use Build accepted changes to update the product.':''}`);}
    catch(caught){setError(caught instanceof Error?caught.message:'The intent could not be saved.');const status=(caught as {status?:number}).status;if(status&&status>=400&&status<500){pending.current=undefined;persistPending();}}
    finally{setBusy(false);}
  }
  async function build(){if(busy)return;setBusy(true);setError('');try{buildRequest.current||=crypto.randomUUID();await onBuild(buildRequest.current);buildRequest.current=undefined;setMessage('Accepted changes queued for the shared builder.');}catch(caught){setError(caught instanceof Error?caught.message:'Build could not be requested.');}finally{setBusy(false);}}
  return <dialog ref={dialog} className="intent-review" aria-labelledby="intent-review-title" onKeyDown={event=>{if(event.key!=='Tab')return;const controls=[...dialog.current!.querySelectorAll<HTMLElement>('button,input,textarea,select,summary,a[href],[tabindex]')].filter(element=>element.tabIndex>=0&&!element.matches(':disabled')&&element.getClientRects().length>0);const first=controls[0],last=controls.at(-1);if(!first)return;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}} onCancel={event=>{event.preventDefault();if(!busy)onClose();}}>
    <header><h2 id="intent-review-title">Shared intent details</h2><button type="button" aria-label="Close intent details" disabled={busy} onClick={onClose}>Close</button></header>
    <div className="intent-review-body"><p>Specification r{shownRevision}{historical?' · historical, read only':''}. Corrections apply only to your own recorded support. Writing or deleting canvas text does not withdraw accepted intent.</p>
      {cacheError&&<p role="alert">{cacheError}</p>}{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}
      {edit&&<form className="intent-correction" onSubmit={event=>void submit(event)}><h3>{edit.action==='withdraw'?'Withdraw your support':'Correct your intent'}</h3><p>Reviewing specification r{edit.specificationRevision}. {edit.action==='withdraw'?'Other contributors’ support will remain. Confirm this explicit withdrawal.':''}</p>
        <fieldset disabled={busy||!!pending.current}><legend>Your correction</legend>{edit.action==='correct'?<><label>Intent text<textarea autoFocus required maxLength={2000} value={edit.text} onChange={event=>setEdit({...edit,text:event.target.value})}/></label>
          <label>Category<select value={edit.category} onChange={event=>setEdit({...edit,category:event.target.value as InterpretationIntentCategory})}>{['goal','feature','design','constraint','question'].map(value=><option key={value} value={value}>{value}</option>)}</select></label>
          <label>Treat as<select value={edit.classification} onChange={event=>setEdit({...edit,classification:event.target.value as Edit['classification']})}><option value="explicit_request">Explicit request</option><option value="proposal">Proposal</option><option value="question">Question</option></select></label></>:<p>{edit.text}</p>}</fieldset>
        <button type="submit" disabled={busy||edit.action==='correct'&&!edit.text.trim()}>{busy?'Saving…':pending.current?'Retry same intent request':edit.action==='withdraw'?'Confirm withdrawal':'Save intent correction'}</button>
        <button type="button" disabled={busy||!!pending.current} onClick={()=>{setEdit(undefined);setError('');}}>Cancel edit</button></form>}
      {state.intentBuildPending&&<div className="intent-build-pending"><p>Accepted intent changed. The previous product remains available.</p>{canEdit&&<button type="button" disabled={busy||state.ai.status!=='connected'} onClick={()=>void build()}>Build accepted changes</button>}</div>}
      <h3>{historical?'Accepted requirement history':'Recorded requirements'}</h3>
      {requirements.map(requirement=><article key={requirement.id}><span>{requirement.status} · {requirement.category} · requirement r{requirement.revision} · {requirement.authority}</span><strong>{requirement.description}</strong>
        <details><summary>Criteria and attributable sources</summary>{requirement.acceptanceCriteria.map((criterion,index)=><p key={index}>{criterion}</p>)}{sources(requirement.sources)}</details>
        {!historical&&canEdit&&requirement.sources.some(source=>source.participantId===participantId)&&<div className="intent-actions"><button type="button" disabled={busy||!!edit} onClick={()=>begin({kind:'requirement',id:requirement.id,revision:requirement.revision},requirement.description,requirement.category,requirement.status==='accepted'?'explicit_request':'proposal','correct')}>Correct my support</button><button type="button" disabled={busy||!!edit} onClick={()=>begin({kind:'requirement',id:requirement.id,revision:requirement.revision},requirement.description,requirement.category,'explicit_request','withdraw')}>Withdraw my support</button></div>}</article>)}
      {!historical&&<><h3>Current interpretations</h3>{state.participants.map(participant=>participant.latest&&<section key={participant.id}><h4>{participant.name} · interpretation r{participant.latest.revision}</h4>{participant.latest.intents?.map(intent=><article key={intent.id}><span>{intent.withdrawn?'Withdrawn':caption(intent.classification)} · {intent.category} · {intent.authority?.replaceAll('_',' ')||'legacy interpretation'}</span><strong>{intent.text}</strong><p>{intent.validation?.reason||intent.rationale}</p><small>Source: “{intent.sourcePassage}” · document r{intent.sourceRevision} · edits {intent.sourceEditSeqs.join(', ')||'recorded correction'}</small>{intent.contextReferences?.map(reference=><small key={reference.requirementId}>Accepted context {reference.requirementId} r{reference.revision} · authors {reference.participantIds.join(', ')}</small>)}
        {canEdit&&participant.id===participantId&&!intent.withdrawn&&<div className="intent-actions"><button type="button" disabled={busy||!!edit} onClick={()=>begin({kind:'interpretation',id:participant.latest!.id,intentId:intent.id,revision:participant.latest!.revision},intent.text,intent.category,intent.classification,'correct')}>Correct my intent</button><button type="button" disabled={busy||!!edit} onClick={()=>begin({kind:'interpretation',id:participant.latest!.id,intentId:intent.id,revision:participant.latest!.revision},intent.text,intent.category,intent.classification,'withdraw')}>Withdraw my intent</button></div>}</article>)}</section>)}</>}
      <details><summary>Correction and interpretation history</summary>{state.intentCorrections?.map(record=><article key={record.requestId}><span>{record.participantName} · {record.action} · {new Date(record.recordedAt).toLocaleString()}</span><p>Before: {record.before}</p>{record.after&&<p>After: {record.after}</p>}{sources(record.sources)}</article>)}{state.interpretationHistory?.map((record,index)=><article key={`${record.id}-${record.revision}-${index}`}><span>{record.participantName} · interpretation r{record.revision}</span>{record.intents?.map(intent=><p key={intent.id}>{caption(intent.classification)}: {intent.text} · “{intent.sourcePassage}” · document r{intent.sourceRevision}</p>)}</article>)}</details>
    </div>
  </dialog>;
}
