import { useCallback, useEffect, useMemo, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { Archive, ChevronLeft, FolderPlus, LogOut, Menu, Search, Sparkles, UserRound, X } from 'lucide-react';
import { Workspace } from './App';
import { needsSessionRefresh } from './auth-session';
import { authReturnKey, safeLocalDestination, supabase, supabaseConfigurationError, supabaseOAuthRedirectUrl } from './supabase';

type ProjectRole='owner'|'editor'|'viewer';
type Project={id:string;ownerId:string;title:string;workflowMode:'developer'|'analyst'|'researcher';archivedAt?:string;createdAt:string;updatedAt:string;role:ProjectRole};
type ProjectList={projects:Project[];total:number;nextOffset:number|null};

async function request<T>(path:string,session:Session,init:RequestInit={},allowRefreshRetry=true):Promise<T>{let current=session;if(needsSessionRefresh(current.expires_at)){const refreshed=await supabase?.auth.refreshSession();if(refreshed?.error||!refreshed?.data.session)throw new Error('Your session expired. Sign in again.');current=refreshed.data.session}const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${current.access_token}`,...init.headers}});if(response.status===401&&allowRefreshRetry&&supabase){const refreshed=await supabase.auth.refreshSession();if(!refreshed.error&&refreshed.data.session)return request<T>(path,refreshed.data.session,init,false)}const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body as T}
const selectedId=()=>location.pathname.match(/^\/projects\/([0-9a-f-]{36})$/i)?.[1]||'';

function ConfigurationError(){return <main className="auth-screen"><section className="auth-card"><Sparkles/><p className="kicker">CoCreate</p><h1>Authentication needs configuration</h1><p>{supabaseConfigurationError}</p><p className="form-error">No local or invitation-only fallback is used in hosted mode.</p></section></main>}

function Login(){const[busy,setBusy]=useState(false),[error,setError]=useState('');const signIn=async()=>{if(!supabase)return;setBusy(true);setError('');sessionStorage.setItem(authReturnKey,safeLocalDestination(new URLSearchParams(location.search).get('returnTo')));const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:supabaseOAuthRedirectUrl,scopes:'openid email profile'}});if(error){setError(error.message);setBusy(false)}};return <main className="auth-screen"><section className="auth-card"><div className="brand-mark"><Sparkles/></div><p className="kicker">CoCreate</p><h1>Build together</h1><p>Sign in to open your private projects, collaborate in the shared canvas, and reopen durable work from any device.</p>{new URLSearchParams(location.search).get('error')&&<p className="form-error">Google sign-in was cancelled or denied. Nothing was changed.</p>}{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy} onClick={()=>void signIn()}>{busy?'Opening Google…':'Continue with Google'}</button><small>CoCreate requests only basic identity information. It does not request Drive or Gmail access.</small></section></main>}

function Callback(){const[error,setError]=useState('');useEffect(()=>{let active=true;const finish=async()=>{if(!supabase)return;const params=new URLSearchParams(location.search),oauthError=params.get('error_description')||params.get('error');if(oauthError){location.replace(`/login?error=denied`);return}const code=params.get('code');if(!code){setError('The sign-in callback did not contain an authorization code.');return}const{error}=await supabase.auth.exchangeCodeForSession(code);if(!active)return;if(error){setError(error.message);return}const destination=safeLocalDestination(sessionStorage.getItem(authReturnKey));sessionStorage.removeItem(authReturnKey);location.replace(destination)};void finish();return()=>{active=false}},[]);return <main className="auth-screen"><section className="auth-card"><Sparkles/><h1>{error?'Sign-in could not finish':'Finishing sign-in…'}</h1>{error&&<><p className="form-error">{error}</p><a href="/login">Return to sign in</a></>}</section></main>}

function AcceptInvite({session,token}:{session:Session;token:string}){const[error,setError]=useState('');useEffect(()=>{let active=true;const accept=async()=>{try{const result=await request<{projectId:string}>('/api/invites/accept',session,{method:'POST',body:JSON.stringify({token})});if(active)location.replace(`/projects/${result.projectId}`)}catch(error){if(active)setError(error instanceof Error?error.message:'The invitation could not be accepted.')}};void accept();return()=>{active=false}},[session,token]);return <main className="auth-screen"><section className="auth-card"><Sparkles/><h1>{error?'Invitation unavailable':'Joining project…'}</h1>{error&&<><p className="form-error">{error}</p><a href="/projects">Return to projects</a></>}</section></main>}

function Sidebar({projects,selected,onCreate,onSelect,onArchive,onSignOut,open,onClose,userName}:{projects:Project[];selected:string;onCreate:()=>void;onSelect:(id:string)=>void;onArchive:(project:Project)=>void;onSignOut:()=>void;open:boolean;onClose:()=>void;userName:string}){const[query,setQuery]=useState(''),filtered=projects.filter(project=>project.title.toLowerCase().includes(query.toLowerCase())),owned=filtered.filter(project=>project.role==='owner'),shared=filtered.filter(project=>project.role!=='owner');return <aside className={`project-sidebar ${open?'open':''}`} aria-label="Projects"><header><strong>CoCreate</strong><button aria-label="Close projects" className="mobile-only" onClick={onClose}><X/></button></header><button className="new-project" onClick={onCreate}><FolderPlus/>New project</button><label className="project-search"><Search/><span className="sr-only">Search projects</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects"/></label><nav><ProjectGroup title="Your projects" projects={owned} selected={selected} onSelect={onSelect} onArchive={onArchive}/><ProjectGroup title="Shared with you" projects={shared} selected={selected} onSelect={onSelect} onArchive={onArchive}/></nav><footer><div><UserRound/><span>{userName}</span></div><button aria-label="Sign out" title="Sign out" onClick={onSignOut}><LogOut/></button></footer></aside>}
function ProjectGroup({title,projects,selected,onSelect,onArchive}:{title:string;projects:Project[];selected:string;onSelect:(id:string)=>void;onArchive:(project:Project)=>void}){return <section><h2>{title}</h2>{projects.length?projects.map(project=><div className={`project-row ${selected===project.id?'selected':''}`} key={project.id}><button onClick={()=>onSelect(project.id)}>{project.title}<small>{project.workflowMode} · {project.role}</small></button>{project.role==='owner'&&<button aria-label={`Archive ${project.title}`} title="Archive" onClick={()=>onArchive(project)}><Archive/></button>}</div>):<p>No projects here.</p>}</section>}

function ProjectWorkspace({project,session,refresh}:{project:Project;session:Session;refresh:()=>void}){const[ticket,setTicket]=useState(''),[error,setError]=useState(''),[inviteBusy,setInviteBusy]=useState(false);useEffect(()=>{let active=true,timer:number;const issue=async()=>{try{const result=await request<{token:string;expiresAt:string}>(`/api/projects/${project.id}/session`,session,{method:'POST'});if(!active)return;setTicket(result.token);setError('');const delay=Math.max(30_000,new Date(result.expiresAt).getTime()-Date.now()-60_000);timer=window.setTimeout(issue,delay)}catch(error){if(active)setError(error instanceof Error?error.message:'Could not open project.')}};void issue();return()=>{active=false;clearTimeout(timer)}},[project.id,session]);const invite=async()=>{setInviteBusy(true);try{const result=await request<{token:string}>(`/api/projects/${project.id}/invites`,session,{method:'POST',body:JSON.stringify({role:'editor'})});await navigator.clipboard.writeText(`${location.origin}/invite/${result.token}`)}catch(error){setError(error instanceof Error?error.message:'Could not create invite.')}finally{setInviteBusy(false)}};if(error)return <main className="project-loading"><p className="form-error">{error}</p><button onClick={refresh}>Try again</button></main>;if(!ticket)return <main className="project-loading">Opening {project.title}…</main>;return <Workspace id={project.id} tokenOverride={ticket} projectTitle={project.title} onInvite={project.role==='owner'?invite:undefined} inviteBusy={inviteBusy}/>}

function Projects({session}:{session:Session}){const[list,setList]=useState<ProjectList>({projects:[],total:0,nextOffset:null}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState(false),[reload,setReload]=useState(0),id=selectedId();const load=useCallback(async()=>{setLoading(true);try{setList(await request<ProjectList>('/api/projects?limit=50',session));setError('')}catch(error){setError(error instanceof Error?error.message:'Could not load projects.')}finally{setLoading(false)}},[session]);useEffect(()=>{void load()},[load,reload]);const navigate=(projectId:string)=>{history.pushState({},'',`/projects/${projectId}`);setDrawer(false);setReload(value=>value+1)};useEffect(()=>{const pop=()=>setReload(value=>value+1);addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);const create=async()=>{try{const project=await request<Project>('/api/projects',session,{method:'POST',body:JSON.stringify({title:'Untitled project',workflowMode:'developer'})});await load();navigate(project.id)}catch(error){setError(error instanceof Error?error.message:'Could not create project.')}};const archive=async(project:Project)=>{try{await request(`/api/projects/${project.id}`,session,{method:'PATCH',body:JSON.stringify({archived:true})});if(id===project.id)history.replaceState({},'','/projects');await load()}catch(error){setError(error instanceof Error?error.message:'Could not archive project.')}};const signOut=async()=>{sessionStorage.clear();Object.keys(localStorage).filter(key=>key.startsWith('cocreate-session-')||key.startsWith('cocreate-product-storage-')).forEach(key=>localStorage.removeItem(key));await supabase?.auth.signOut();location.replace('/login')};const selected=list.projects.find(project=>project.id===id);return <main className="project-app"><button className="project-menu mobile-only" aria-label="Open projects" onClick={()=>setDrawer(true)}><Menu/></button><Sidebar projects={list.projects} selected={id} onCreate={()=>void create()} onSelect={navigate} onArchive={project=>void archive(project)} onSignOut={()=>void signOut()} open={drawer} onClose={()=>setDrawer(false)} userName={String(session.user.user_metadata.full_name||session.user.email||'Profile')}/><section className="project-main">{error&&<div className="error-banner">{error}</div>}{loading&&!selected?<div className="project-loading">Loading projects…</div>:selected?<ProjectWorkspace project={selected} session={session} refresh={()=>setReload(value=>value+1)}/>:<div className="project-empty"><Sparkles/><h1>Your shared work starts here</h1><p>Create a private project. No model is called until a participant explicitly submits changes.</p><button className="primary" onClick={()=>void create()}><FolderPlus/>New project</button></div>}</section></main>}

export function ProjectApp(){const[session,setSession]=useState<Session|null|undefined>(undefined);useEffect(()=>{let active=true;if(!supabase){setSession(null);return}void supabase.auth.getSession().then(({data})=>{if(active)setSession(data.session)});const{data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>{active=false;data.subscription.unsubscribe()}},[]);if(supabaseConfigurationError)return <ConfigurationError/>;if(location.pathname==='/api/auth/callback'||location.pathname==='/auth/callback')return <Callback/>;if(session===undefined)return <main className="project-loading">Restoring your session…</main>;if(!session){if(location.pathname!=='/login'){const intended=safeLocalDestination(`${location.pathname}${location.search}`);location.replace(`/login?returnTo=${encodeURIComponent(intended)}`);return null}return <Login/>}const inviteToken=location.pathname.match(/^\/invite\/([^/]+)$/)?.[1];if(inviteToken)return <AcceptInvite session={session} token={decodeURIComponent(inviteToken)}/>;if(location.pathname==='/login'||location.pathname==='/')location.replace('/projects');return <Projects session={session}/>}
