import type { RoomView } from './types';
export function WorkflowBoard({state, onCanvas, onArtifacts}: {state: RoomView; onCanvas: () => void; onArtifacts: () => void}) {
  const tasks = state.workflow.tasks;
  const lastBuild=state.aiRuns.at(-1);
  const recentCalls=state.providerCalls.filter(call=>call.outcome!=='dispatching').slice(-5).reverse();
  const recorded=state.physicalUsage;
  const hasReported=state.providerCalls.some(call=>call.usage.inputTokens!==undefined||call.usage.outputTokens!==undefined)||recorded.recorded.inputTokens+recorded.recorded.outputTokens>0;
  const recordedTokens=recorded.recorded.inputTokens+recorded.recorded.outputTokens;
  const tokens=(value:number|undefined)=>value===undefined?'Unavailable':value.toLocaleString();
  const charge=!lastBuild?'—':lastBuild.usage.estimatedChargeUsd===undefined?'Unknown':`${lastBuild.usage.estimatedChargeUsd.toFixed(3)} estimated${lastBuild.usage.chargeIncomplete?' · partial':''}`;
  return <section className="workflow-board">
    <header><span className="section-eyebrow">Team workspace · revision {state.workflow.revision}</span><h1>From idea to working product.</h1><p>Write together. Submit your changes. Follow the work here.</p><button className="primary" onClick={onCanvas}>Open canvas →</button></header>
    <div className="workflow-stats"><article><span>Workflow</span><strong>{state.workflow.phase.replaceAll('_', ' ')}</strong></article><article><span>Accepted requirements</span><strong>{state.requirements.filter(item => item.status === 'accepted').length}</strong></article><article><span>Latest artifact</span><strong>{state.latestVersion ? `v${state.latestVersion}` : 'Not built yet'}</strong>{state.latestVersion && <button onClick={onArtifacts}>View product →</button>}</article></div>
    <section id="workflow-usage" className="workflow-usage" aria-labelledby="workflow-usage-title"><h2 id="workflow-usage-title">Usage</h2><dl><div><dt>Last build status</dt><dd>{lastBuild?lastBuild.outcome:'No build yet'}</dd></div><div><dt>Last build charge</dt><dd>{charge}</dd></div><div><dt>Recorded physical calls</dt><dd>{recorded.recorded.requests} recorded attempts · {hasReported?recordedTokens.toLocaleString():'Unknown'} reported tokens</dd></div><div><dt>Generation calls</dt><dd>{recorded.generation.requests} calls · {(recorded.generation.inputTokens+recorded.generation.outputTokens).toLocaleString()} reported tokens</dd></div><div><dt>Setup tests</dt><dd>{recorded.setup.requests} calls · {(recorded.setup.inputTokens+recorded.setup.outputTokens).toLocaleString()} reported tokens</dd></div><div><dt>Historical generation counter</dt><dd>{(state.usage.inputTokens+state.usage.outputTokens).toLocaleString()} tokens</dd></div></dl><details><summary>Recent provider calls · last {recentCalls.length} recorded</summary>{recentCalls.length?<ol>{recentCalls.map(call=><li key={call.callId}>{call.purpose.replaceAll('_',' ')} · {tokens(call.usage.inputTokens)} input / {tokens(call.usage.outputTokens)} output tokens{call.usageStatus!=='measured'?' · usage incomplete':''}</li>)}</ol>:<p>No provider calls recorded yet.</p>}</details><small>Physical-call coverage is partial{recorded.recordedFrom?` from ${new Date(recorded.recordedFrom).toLocaleDateString()}`:''}. Workflow scope: recorded generation includes interpretation, builder, recovery, and repair attempts; setup tests are separate. Cumulative usage is not context-window occupancy. Earlier calls may be missing; {recorded.unknownUsageRequests} recorded calls have incomplete or unknown usage. The historical generation counter is retained separately and is not added to physical calls.</small></section>
    <section><h2>Work in progress</h2>{tasks.length ? <ol className="workflow-task-list">{tasks.map(task => <li key={task.id}><div><strong>{task.title}</strong><span className="task-state">{task.state.replaceAll('_', ' ')}</span></div><p>Verification: {task.evidenceStatus}</p>{task.blocker && <p className="form-error">{task.blocker}</p>}</li>)}</ol> : <p className="workflow-empty">No submitted tasks yet. Writing is free of model calls; use Build my changes when ready.</p>}</section>
    <details><summary>Recent activity · {state.workflow.activity.length}</summary><ol className="workflow-activity">{state.workflow.activity.slice(-12).reverse().map(event => <li key={event.sequence}><span>{event.summary}</span><time dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}</time></li>)}</ol></details>
  </section>;
}
